title: "Civic Lab"
description: "A learn-by-doing action tank for the Baltimore–DC region."
theme: minima

# URL Settings
url: "https://adam7234.github.io" # Root hostname
baseurl: "/civiclab"                  # The subpath (the name of your repo)

# Navigation
header_pages:
  - about.md
  - team.md

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
